### ISSUE TITLE
Name Overflowing 

### ISSUE THREAD

**Issue by Shreshtth** [madushadhanushka/github-readme#4]
Hey, I recently was looking for some **cool widgets** to add to my GitHub profile  when I came across your widgets repo. 

There is a small issue, I want to report. The names of some repos, I worked on are too-long to fit in Top Repository section and **ruins the whole Widget's UI**. Hope we get a fix on this soon. 

![image](https://github.com/user-attachments/assets/61cd8dfe-f093-4938-966d-db935d50894c)

Thank You!

**Comment by madushadhanushka** [comment]
Seems you are using @PressJump [reimaginedreadme](https://github.com/PressJump/reimaginedreadme) and this issue should be raised there. But this repo has a deprecation notice and might have to find another widget doing the same.
